{
  "Groups": [
    {
      "name": "cn=group1,ou=groups,dc=example,dc=com",
      "profiles": [
        {
            "display_name": "Demo - choose me!!",
            "slug": "Demo-python",
            "default": true,
            "kubespawner_override": {
                "image": "quay.io/ypery/jup-minimal-py37-notebook:latest",
                "cpu_limit": 1,
                "mem_limit": "512M"
            }
        },{
            "display_name": "Training Env - Python",
            "slug": "training-python",
            "default": true,
            "kubespawner_override": {
                "image": "training/python:label",
                "cpu_limit": 1,
                "mem_limit": "512M"
            }
        }          
      ]
    }, {
      "name": "cn=group2,ou=groups,dc=example,dc=com",
      "profiles": [
        {
            "display_name": "Demo2 - choose me!!",
            "slug": "Demo-python",
            "default": true,
            "kubespawner_override": {
                "image": "quay.io/ypery/jup-minimal-py37-notebook:latest",
                "cpu_limit": 1,
                "mem_limit": "512M"
            }
        },{
            "display_name": "Training Env2 - Python",
            "slug": "training-python",
            "default": true,
            "kubespawner_override": {
                "image": "training/python:label",
                "cpu_limit": 1,
                "mem_limit": "512M"
            }
        }
      ]
    }, {
      "name": "group7",
      "profiles": [
        {
            "display_name": "Demo7 - choose me!!",
            "slug": "Demo-python",
            "default": true,
            "kubespawner_override": {
                "image": "quay.io/ypery/jup-minimal-py37-notebook:latest",
                "cpu_limit": 1,
                "mem_limit": "512M"
            }
        },{
            "display_name": "Training Env7 - Python",
            "slug": "training-python",
            "default": true,
            "kubespawner_override": {
                "image": "training/python:label",
                "cpu_limit": 1,
                "mem_limit": "512M"
            }
        }
      ]
    }

  ]
}